# Generated by Django 4.2.30 on 2026-09-04 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_agenda', models.CharField(max_length=30, verbose_name='Nomor Agenda')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('asal_surat', models.CharField(max_length=150, verbose_name='Asal Surat')),
                ('perihal', models.CharField(max_length=255, verbose_name='Perihal')),
                ('sifat', models.CharField(choices=[('biasa', 'Biasa'), ('penting', 'Penting'), ('segera', 'Segera'), ('rahasia', 'Rahasia')], default='biasa', max_length=10)),
                ('tanggal_surat', models.DateField(verbose_name='Tanggal Surat')),
                ('tanggal_diterima', models.DateField(verbose_name='Tanggal Diterima')),
                ('file_scan', models.FileField(upload_to='surat_masuk/%Y/%m/', verbose_name='File Scan Surat')),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('dicatat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_masuk_dicatat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surat Masuk',
                'verbose_name_plural': 'Surat Masuk',
                'ordering': ['-tanggal_diterima', '-dicatat_pada'],
            },
        ),
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_agenda', models.CharField(max_length=30, verbose_name='Nomor Agenda')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('tujuan_surat', models.CharField(max_length=150, verbose_name='Tujuan Surat')),
                ('perihal', models.CharField(max_length=255, verbose_name='Perihal')),
                ('sifat', models.CharField(choices=[('biasa', 'Biasa'), ('penting', 'Penting'), ('segera', 'Segera'), ('rahasia', 'Rahasia')], default='biasa', max_length=10)),
                ('tanggal_surat', models.DateField(verbose_name='Tanggal Surat')),
                ('file_scan', models.FileField(upload_to='surat_keluar/%Y/%m/', verbose_name='File Surat')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_keluar_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surat Keluar',
                'verbose_name_plural': 'Surat Keluar',
                'ordering': ['-tanggal_surat', '-dibuat_pada'],
            },
        ),
    ]
