# Generated by Django 4.2.30 on 2026-09-09 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persuratan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_tujuan', models.JSONField(default=list, verbose_name='Ditujukan Kepada')),
                ('instruksi', models.JSONField(default=list, verbose_name='Instruksi/Informasi')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Tindak Lanjut'), ('ditindaklanjuti', 'Sudah Ditindaklanjuti')], default='menunggu', max_length=20)),
                ('tanggal_disposisi', models.DateTimeField(auto_now_add=True)),
                ('tanggal_tindak_lanjut', models.DateTimeField(blank=True, null=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposisi_dibuat', to=settings.AUTH_USER_MODEL)),
                ('ditindaklanjuti_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposisi_ditindaklanjuti', to=settings.AUTH_USER_MODEL)),
                ('surat_masuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposisi', to='persuratan.suratmasuk')),
            ],
            options={
                'verbose_name': 'Disposisi',
                'verbose_name_plural': 'Disposisi',
                'ordering': ['-tanggal_disposisi'],
            },
        ),
    ]
