# Generated by Django 4.2.30 on 2026-08-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databarang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_kerja', models.CharField(max_length=100, verbose_name='Unit Kerja Pemilik')),
                ('kode_barang', models.CharField(max_length=30, verbose_name='Kode Barang')),
                ('nama_barang', models.CharField(max_length=150, verbose_name='Nama Barang')),
                ('satuan', models.CharField(choices=[('pcs', 'Pcs'), ('rim', 'Rim'), ('box', 'Box'), ('botol', 'Botol'), ('lusin', 'Lusin'), ('pak', 'Pak'), ('unit', 'Unit')], default='pcs', max_length=10)),
                ('stok', models.PositiveIntegerField(default=0, verbose_name='Stok Tersedia')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stok Barang Unit',
                'verbose_name_plural': 'Stok Barang Unit',
                'ordering': ['nama_barang'],
                'unique_together': {('unit_kerja', 'kode_barang')},
            },
        ),
    ]
