# Generated by Django 4.2.30 on 2026-08-14 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databarang', '0002_stokunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermintaanDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_kerja', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='diajukan', max_length=10)),
                ('catatan_approval', models.TextField(blank=True)),
                ('diajukan_pada', models.DateTimeField(auto_now_add=True)),
                ('diproses_pada', models.DateTimeField(blank=True, null=True)),
                ('diajukan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permintaan_dinas_diajukan', to=settings.AUTH_USER_MODEL)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permintaan_dinas_diproses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permintaan Ke Dinas',
                'verbose_name_plural': 'Permintaan Ke Dinas',
                'ordering': ['-diajukan_pada'],
            },
        ),
        migrations.CreateModel(
            name='PermintaanDinasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databarang.barangatk')),
                ('permintaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='databarang.permintaandinas')),
            ],
        ),
    ]
