# Generated by Django 4.2.30 on 2026-08-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databarang', '0003_permintaandinas_permintaandinasitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangatk',
            name='kategori',
            field=models.CharField(choices=[('atk', 'ATK'), ('bhp', 'BHP')], default='atk', max_length=5),
        ),
    ]
