# Generated by Django 4.2.30 on 2026-09-15 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermintaanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asal_instansi', models.CharField(max_length=200, verbose_name='Asal Instansi/Kampus')),
                ('keperluan', models.CharField(max_length=255, verbose_name='Keperluan')),
                ('data_diminta', models.TextField(verbose_name='Data yang Diminta')),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='diajukan', max_length=10)),
                ('catatan_tanggapan', models.TextField(blank=True, verbose_name='Catatan Tanggapan')),
                ('diajukan_pada', models.DateTimeField(auto_now_add=True)),
                ('diproses_pada', models.DateTimeField(blank=True, null=True)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permintaan_data_diproses', to=settings.AUTH_USER_MODEL)),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permintaan Data',
                'verbose_name_plural': 'Permintaan Data',
                'ordering': ['-diajukan_pada'],
            },
        ),
    ]
