# Generated by Django 4.2.30 on 2026-09-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permintaandata',
            name='nama_pemohon',
            field=models.CharField(default='-', max_length=150, verbose_name='Nama Pemohon'),
            preserve_default=False,
        ),
    ]
