# Generated by Django 4.2.30 on 2026-07-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=20, unique=True, verbose_name='Kode Barang')),
                ('nama_barang', models.CharField(max_length=150, verbose_name='Nama Barang')),
                ('merk', models.CharField(max_length=100, verbose_name='Merk')),
                ('tipe', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aset',
                'verbose_name_plural': 'Aset',
                'ordering': ['kode_barang'],
            },
        ),
    ]
