# Generated by Django 4.2.30 on 2026-07-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aset',
            new_name='Asset',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['kode_barang'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Asset'},
        ),
    ]
