# Generated by Django 4.2.30 on 2026-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_rename_aset_asset_alter_asset_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='merk',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tipe',
        ),
        migrations.AddField(
            model_name='asset',
            name='merk_type',
            field=models.CharField(default='', max_length=150, verbose_name='Merk / Type'),
            preserve_default=False,
        ),
    ]
