# Generated by Django 4.2.30 on 2026-07-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_remove_asset_merk_remove_asset_tipe_asset_merk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='kondisi',
            field=models.CharField(choices=[('baik', 'Baik'), ('buruk', 'Buruk')], default='baik', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='kode_barang',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kode Barang'),
        ),
    ]
