# Generated by Django 4.2.30 on 2026-07-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_kondisi_alter_asset_kode_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='keterangan',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
    ]
