# Generated by Django 4.2.30 on 2026-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_asset_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kondisi',
            field=models.CharField(choices=[('baik', 'Baik'), ('kurang baik', 'kurang baik'), ('rusak', 'rusak')], default='baik', max_length=15),
        ),
    ]
