# Generated by Django 4.2.30 on 2026-08-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_asset_kondisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='lokasi',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lokasi'),
        ),
        migrations.AddField(
            model_name='asset',
            name='pengguna',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pengguna/Pemegang Saat Ini'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='kondisi',
            field=models.CharField(choices=[('baik', 'Baik'), ('kurang_baik', 'Kurang Baik'), ('rusak', 'Rusak')], default='baik', max_length=15),
        ),
    ]
