# Generated by Django 4.2.30 on 2026-08-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_asset_lokasi_asset_pengguna_alter_asset_kondisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='lokasi',
            field=models.CharField(blank=True, choices=[('Ruang Tamu DPPKB', 'Ruang Tamu DPPKB'), ('Bagian Umum dan Kepegawaian DPPKB', 'Bagian Umum dan Kepegawaian DPPKB'), ('Ruang Kepala Dinas DPPKB', 'Ruang Kepala Dinas DPPKB'), ('Ruang Alat Kontrasepsi DPPKB', 'Ruang Alat Kontrasepsi DPPKB'), ('Sekretariat Genre DPPKB', 'Sekretariat Genre DPPKB'), ('Mushollah DPPKB', 'Mushollah DPPKB'), ('Dapur DPPKB', 'Dapur DPPKB'), ('Aula Bangga Kencana DPPKB', 'Aula Bangga Kencana DPPKB'), ('Gudang DPPKB', 'Gudang DPPKB'), ('Bagian Keuangan DPPKB', 'Bagian Keuangan DPPKB'), ('Bagian Program dan Perencanaan DPPKB', 'Bagian Program dan Perencanaan DPPKB'), ('Ruang Sekretaris DPPKB', 'Ruang Sekretaris DPPKB'), ('Bidang KB DPPKB', 'Bidang KB DPPKB'), ('Bidang DaldukP2 DPPKB', 'Bidang DaldukP2 DPPKB'), ('Bidang K3 DPPKB', 'Bidang K3 DPPKB'), ('Ruang Kepala Bidang K3 DPPKB', 'Ruang Kepala Bidang K3 DPPKB')], max_length=100, verbose_name='Lokasi'),
        ),
    ]
