# Generated by Django 4.2.30 on 2026-08-12 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0008_alter_asset_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='nomor_identitas',
            field=models.CharField(blank=True, max_length=255, verbose_name='No. Sertifikat/Pabrik/Chasis/Mesin'),
        ),
        migrations.AddField(
            model_name='asset',
            name='register',
            field=models.CharField(blank=True, max_length=20, verbose_name='Register'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tahun_pembelian',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahun Pembelian'),
        ),
        migrations.CreateModel(
            name='RiwayatService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_service', models.CharField(max_length=150, verbose_name='Jenis Service/Pemeliharaan')),
                ('keterangan', models.TextField(blank=True)),
                ('biaya', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_service', to='asset.asset')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Service',
                'verbose_name_plural': 'Riwayat Service',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
