# Generated by Django 4.2.30 on 2026-08-12 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0009_asset_nomor_identitas_asset_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermintaanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_service', models.CharField(max_length=150, verbose_name='Jenis Service/Pemeliharaan')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan/Alasan Pengajuan')),
                ('biaya_estimasi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='diajukan', max_length=10)),
                ('catatan_approval', models.TextField(blank=True)),
                ('diajukan_pada', models.DateTimeField(auto_now_add=True)),
                ('diproses_pada', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan_service', to='asset.asset')),
                ('diajukan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_diajukan', to=settings.AUTH_USER_MODEL)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_diproses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permintaan Service',
                'verbose_name_plural': 'Permintaan Service',
                'ordering': ['-diajukan_pada'],
            },
        ),
        migrations.AddField(
            model_name='riwayatservice',
            name='permintaan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat', to='asset.permintaanservice'),
        ),
    ]
