# Generated by Django 4.2.30 on 2026-08-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_permintaanservice_riwayatservice_permintaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='lokasi',
            field=models.CharField(blank=True, choices=[('Ruang Tamu DPPKB', 'Ruang Tamu DPPKB'), ('Bagian Umum dan Kepegawaian DPPKB', 'Bagian Umum dan Kepegawaian DPPKB'), ('Ruang Kepala Dinas DPPKB', 'Ruang Kepala Dinas DPPKB'), ('Ruang Alat Kontrasepsi DPPKB', 'Ruang Alat Kontrasepsi DPPKB'), ('Sekretariat Genre DPPKB', 'Sekretariat Genre DPPKB'), ('Mushollah DPPKB', 'Mushollah DPPKB'), ('Dapur DPPKB', 'Dapur DPPKB'), ('Aula Bangga Kencana DPPKB', 'Aula Bangga Kencana DPPKB'), ('Gudang DPPKB', 'Gudang DPPKB'), ('Bagian Keuangan DPPKB', 'Bagian Keuangan DPPKB'), ('Bagian Program dan Perencanaan DPPKB', 'Bagian Program dan Perencanaan DPPKB'), ('Ruang Sekretaris DPPKB', 'Ruang Sekretaris DPPKB'), ('Bidang KB DPPKB', 'Bidang KB DPPKB'), ('Bidang DaldukP2 DPPKB', 'Bidang DaldukP2 DPPKB'), ('Bidang K3 DPPKB', 'Bidang K3 DPPKB'), ('Ruang Kepala Bidang K3 DPPKB', 'Ruang Kepala Bidang K3 DPPKB'), ('Balai Loa Janan Ilir', 'Balai Loa Janan Ilir'), ('Balai Palaran', 'Balai Palaran'), ('Balai Samarinda Ilir', 'Balai Samarinda Ilir'), ('Balai Samarinda Kota', 'Balai Samarinda Kota'), ('Balai Samarinda Seberang', 'Balai Samarinda Seberang'), ('Balai Samarinda Ulu', 'Balai Samarinda Ulu'), ('Balai Samarinda Utara', 'Balai Samarinda Utara'), ('Balai Sambutan', 'Balai Sambutan'), ('Balai Sungai Kunjang', 'Balai Sungai Kunjang'), ('Balai Sungai Pinang', 'Balai Sungai Pinang')], max_length=100, verbose_name='Lokasi'),
        ),
    ]
