# Generated by Django 4.2.30 on 2026-08-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_alter_asset_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='kategori',
            field=models.CharField(choices=[('kendaraan', 'Kendaraan'), ('elektronik', 'Elektronik'), ('lainnya', 'Lainnya')], default='lainnya', max_length=15),
        ),
    ]
