# Generated by Django 4.2.30 on 2026-08-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_asset_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tanggal_jatuh_tempo_pajak',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Jatuh Tempo Pajak'),
        ),
    ]
