# Generated by Django 4.2.30 on 2026-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_asset_tanggal_jatuh_tempo_pajak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kode_barang',
            field=models.CharField(max_length=30, verbose_name='Kode Barang'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('kode_barang', 'register')},
        ),
    ]
