# Generated by Django 4.2.30 on 2026-09-03 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0015_alter_asset_kode_barang_alter_asset_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PindahTanganAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pihak_pertama', models.CharField(blank=True, max_length=150)),
                ('lokasi_pihak_pertama', models.CharField(blank=True, max_length=100)),
                ('nama_pihak_kedua', models.CharField(max_length=150, verbose_name='Diserahkan Kepada')),
                ('lokasi_pihak_kedua', models.CharField(choices=[('Ruang Tamu DPPKB', 'Ruang Tamu DPPKB'), ('Bagian Umum dan Kepegawaian DPPKB', 'Bagian Umum dan Kepegawaian DPPKB'), ('Ruang Kepala Dinas DPPKB', 'Ruang Kepala Dinas DPPKB'), ('Ruang Alat Kontrasepsi DPPKB', 'Ruang Alat Kontrasepsi DPPKB'), ('Sekretariat Genre DPPKB', 'Sekretariat Genre DPPKB'), ('Mushollah DPPKB', 'Mushollah DPPKB'), ('Dapur DPPKB', 'Dapur DPPKB'), ('Aula Bangga Kencana DPPKB', 'Aula Bangga Kencana DPPKB'), ('Gudang DPPKB', 'Gudang DPPKB'), ('Bagian Perencanaan Program & Keuangan DPPKB', 'Bagian Perencanaan Program & Keuangan DPPKB'), ('Ruang Sekretaris DPPKB', 'Ruang Sekretaris DPPKB'), ('Bidang KB DPPKB', 'Bidang KB DPPKB'), ('Bidang DaldukP2 DPPKB', 'Bidang DaldukP2 DPPKB'), ('Bidang K3 DPPKB', 'Bidang K3 DPPKB'), ('Ruang Kepala Bidang K3 DPPKB', 'Ruang Kepala Bidang K3 DPPKB'), ('Balai Loa Janan Ilir', 'Balai Loa Janan Ilir'), ('Balai Palaran', 'Balai Palaran'), ('Balai Samarinda Ilir', 'Balai Samarinda Ilir'), ('Balai Samarinda Kota', 'Balai Samarinda Kota'), ('Balai Samarinda Seberang', 'Balai Samarinda Seberang'), ('Balai Samarinda Ulu', 'Balai Samarinda Ulu'), ('Balai Samarinda Utara', 'Balai Samarinda Utara'), ('Balai Sambutan', 'Balai Sambutan'), ('Balai Sungai Kunjang', 'Balai Sungai Kunjang'), ('Balai Sungai Pinang', 'Balai Sungai Pinang')], max_length=100, verbose_name='Lokasi Tujuan')),
                ('status', models.CharField(choices=[('diajukan', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='diajukan', max_length=10)),
                ('catatan_approval', models.TextField(blank=True)),
                ('diajukan_pada', models.DateTimeField(auto_now_add=True)),
                ('diproses_pada', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pindah_tangan', to='asset.asset')),
                ('diajukan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pindah_tangan_diajukan', to=settings.AUTH_USER_MODEL)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pindah_tangan_diproses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pindah Tangan Asset',
                'verbose_name_plural': 'Pindah Tangan Asset',
                'ordering': ['-diajukan_pada'],
            },
        ),
    ]
