# Generated by Django 4.2.30 on 2026-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_pindahtanganasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='nomor_plat',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomor Plat'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='kondisi',
            field=models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], default='baik', max_length=15),
        ),
    ]
