# Generated by Django 4.2.30 on 2026-09-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_asset_nomor_plat_alter_asset_kondisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pindahtanganasset',
            name='jabatan_pihak_kedua',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jabatan Pihak Kedua'),
        ),
        migrations.AddField(
            model_name='pindahtanganasset',
            name='jabatan_pihak_pertama',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jabatan Pihak Pertama'),
        ),
        migrations.AddField(
            model_name='pindahtanganasset',
            name='nip_pihak_kedua',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIP Pihak Kedua'),
        ),
        migrations.AddField(
            model_name='pindahtanganasset',
            name='nip_pihak_pertama',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIP Pihak Pertama'),
        ),
    ]
