# Generated by Django 4.2.30 on 2026-08-05 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('created', 'Ditambahkan'), ('updated', 'Diperbarui'), ('deleted', 'Dihapus')], max_length=10)),
                ('deskripsi', models.CharField(max_length=255)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
