# Generated by Django 4.2.30 on 2026-08-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_alter_profile_unit_kerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator'), ('kasubag_umum', 'Kasubag Umum')], default='operator', max_length=15),
        ),
    ]
