# Generated by Django 4.2.30 on 2026-08-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jenis_akun',
            field=models.CharField(choices=[('umum', 'Umum'), ('balai', 'Balai'), ('bidang', 'Bidang')], default='umum', max_length=10),
        ),
    ]
