# Generated by Django 4.2.30 on 2026-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0004_profile_jenis_akun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unit_kerja',
            field=models.CharField(blank=True, choices=[('Sekretariat', 'Sekretariat'), ('Sub Bagian Perencanaan Program & Keuangan', 'Sub Bagian Perencanaan Program & Keuangan'), ('Sub Bagian Umum dan Kepegawaian', 'Sub Bagian Umum dan Kepegawaian'), ('Bidang Pengendalian Penduduk, Penyuluhan dan Penggerakan', 'Bidang Pengendalian Penduduk, Penyuluhan dan Penggerakan'), ('Bidang KB DPPKB', 'Bidang KB DPPKB'), ('Bidang Ketahanan dan Kesejahteraan Keluarga', 'Bidang Ketahanan dan Kesejahteraan Keluarga')], max_length=100),
        ),
    ]
