# Generated by Django 4.2.30 on 2026-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0005_alter_profile_unit_kerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unit_kerja',
            field=models.CharField(blank=True, choices=[('Sekretariat', 'Sekretariat'), ('Sub Bagian Perencanaan Program & Keuangan', 'Sub Bagian Perencanaan Program & Keuangan'), ('Sub Bagian Umum dan Kepegawaian', 'Sub Bagian Umum dan Kepegawaian'), ('Bidang Pengendalian Penduduk, Penyuluhan dan Penggerakan', 'Bidang Pengendalian Penduduk, Penyuluhan dan Penggerakan'), ('Bidang KB DPPKB', 'Bidang KB DPPKB'), ('Bidang Ketahanan dan Kesejahteraan Keluarga', 'Bidang Ketahanan dan Kesejahteraan Keluarga'), ('Balai Loa Janan Ilir', 'Balai Loa Janan Ilir'), ('Balai Palaran', 'Balai Palaran'), ('Balai Samarinda Ilir', 'Balai Samarinda Ilir'), ('Balai Samarinda Kota', 'Balai Samarinda Kota'), ('Balai Samarinda Seberang', 'Balai Samarinda Seberang'), ('Balai Samarinda Ulu', 'Balai Samarinda Ulu'), ('Balai Samarinda Utara', 'Balai Samarinda Utara'), ('Balai Sambutan', 'Balai Sambutan'), ('Balai Sungai Kunjang', 'Balai Sungai Kunjang'), ('Balai Sungai Pinang', 'Balai Sungai Pinang')], max_length=100),
        ),
    ]
