# Generated by Django 4.2.30 on 2026-08-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0006_alter_profile_unit_kerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unit_kerja',
            field=models.CharField(blank=True, choices=[('Sekretariat', 'Sekretariat'), ('Bagian Perencanaan Program & Keuangan DPPKB', 'Bagian Perencanaan Program & Keuangan DPPKB'), ('Bagian Umum dan Kepegawaian DPPKB', 'Bagian Umum dan Kepegawaian DPPKB'), ('Bidang DaldukP2 DPPKB', 'Bidang DaldukP2 DPPKB'), ('Bidang KB DPPKB', 'Bidang KB DPPKB'), ('Bidang K3 DPPKB', 'Bidang K3 DPPKB'), ('Balai Loa Janan Ilir', 'Balai Loa Janan Ilir'), ('Balai Palaran', 'Balai Palaran'), ('Balai Samarinda Ilir', 'Balai Samarinda Ilir'), ('Balai Samarinda Kota', 'Balai Samarinda Kota'), ('Balai Samarinda Seberang', 'Balai Samarinda Seberang'), ('Balai Samarinda Ulu', 'Balai Samarinda Ulu'), ('Balai Samarinda Utara', 'Balai Samarinda Utara'), ('Balai Sambutan', 'Balai Sambutan'), ('Balai Sungai Kunjang', 'Balai Sungai Kunjang'), ('Balai Sungai Pinang', 'Balai Sungai Pinang')], max_length=100),
        ),
    ]
