# Generated by Django 4.2.30 on 2026-09-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator'), ('kasubag_umum', 'Kasubag Umum'), ('kadis', 'Kepala Dinas'), ('tamu', 'Tamu')], default='operator', max_length=15),
        ),
    ]
